version: "3.8"

services:
  mongo:
    image: mongo:6
    container_name: randomdots-mongo
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - /home/apps/randomdots/mongo_data:/data/db
    environment:
      MONGO_INITDB_DATABASE: randomdots 
    healthcheck:
      test: ["CMD", "mongosh", "--eval", "db.runCommand({ ping: 1 })"]
      interval: 10s
      retries: 5
      start_period: 10s

  app:
    build: .
    container_name: randomdots-app
    restart: always
    ports:
      - "3000:3000"
    volumes:
      - .:/app  
      - /app/node_modules  
    depends_on:
      mongo:
        condition: service_healthy
    env_file:
      - .env  

  nginx:
    image: nginx:latest
    container_name: randomdots-nginx
    restart: always
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - ./public:/usr/share/nginx/html:ro
    depends_on:
      - app

volumes:
  mongo_data:
