version: "3.8"

services:
  mongo:
    image: mongo:6
    container_name: randomdots-mongo
    restart: always
    ports:
      - "127.0.0.1:27017:27017"
    volumes:
      - mongo_data:/data/db 
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_INITDB_ROOT_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_INITDB_ROOT_PASSWORD}
      MONGO_INITDB_DATABASE: ${MONGO_INITDB_DATABASE}
    healthcheck:
      test: ["CMD", "mongosh", "--eval", "db.runCommand({ ping: 1 })"]
      interval: 10s
      retries: 5
      start_period: 10s
    networks:
      - caddy-net

  app:
    build: .
    container_name: randomdots-app
    restart: always
    ports:
      - "3001:3000"
    volumes:
      - .:/app  
      - /app/node_modules
    environment:
      MONGO_URI: ${MONGO_URI}
    depends_on:
      mongo:
        condition: service_healthy
    env_file:
      - .env  
    networks:
      - caddy-net


volumes:
  mongo_data:

networks:
  caddy-net:
    external: true