version: "3.8"

services:
  mongo:
    image: mongo:6
    container_name: randomdots-mongo
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db
    environment:
      MONGO_INITDB_DATABASE: randomdots 
    healthcheck:
      test: ["CMD", "mongosh", "--eval", "db.runCommand({ ping: 1 })"]
      interval: 10s
      retries: 5
      start_period: 10s

  app:
    build: .
    container_name: randomdots-app
    restart: always
    ports:
      - "3000:3000"
    volumes:
      - .:/app  
      - /app/node_modules  
    depends_on:
      mongo:
        condition: service_healthy
    env_file:
      - .env  

volumes:
  mongo_data:
