name: Deploy Randomdots to Droplet

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Set up SSH
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan -H ${{ secrets.SSH_HOST }} >> ~/.ssh/known_hosts
      - name: Deploy on Droplet
        run: |
          ssh ${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }} << 'EOF'
            cd /home/apps/randomdots

            echo "Pulling latest changes..."
            git pull origin main

            echo "Creating/updating .env file..."
            echo "CLOUDINARY_CLOUD_NAME=${{ secrets.CLOUDINARY_CLOUD_NAME }}" > .env
            echo "CLOUDINARY_KEY=${{ secrets.CLOUDINARY_KEY }}" >> .env
            echo "CLOUDINARY_SECRET=${{ secrets.CLOUDINARY_SECRET }}" >> .env
            echo "MAPTILER_API_KEY=${{ secrets.MAPTILER_API_KEY }}" >> .env
            echo "MONGO_INITDB_ROOT_USERNAME=${{ secrets.MONGO_INITDB_ROOT_USERNAME }}" >> .env
            echo "MONGO_INITDB_ROOT_PASSWORD=${{ secrets.MONGO_INITDB_ROOT_PASSWORD }}" >> .env
            echo "MONGO_INITDB_DATABASE=${{ secrets.MONGO_INITDB_DATABASE }}" >> .env
            echo "MONGO_URI=mongodb://${{ secrets.MONGO_INITDB_ROOT_USERNAME }}:${{ secrets.MONGO_INITDB_ROOT_PASSWORD }}@randomdots-mongo:27017/${{ secrets.MONGO_INITDB_DATABASE }}?authSource=admin" >> .env
            echo "NODE_ENV=production" >> .env

            echo "Restarting Docker services..."

            export \$(cat .env | xargs)

            docker compose down
            docker compose up -d --build

            echo "Connecting randomdots containers to caddy-net..."
            docker network connect caddy-net randomdots-app || true
            docker network connect caddy-net randomdots-nginx || true

            echo "Reloading Caddy to apply new config..."
            cd /home/apps/caddy
            docker compose up -d
          EOF
